-- What are Ranking Functions?What are Ranking Functions?
-- Ranking functions assign a position/rank to rows based on an ordering.

-- Student     Marks
-- --------    -----
-- A           95
-- B           90
-- C           85
-- D           80
--    |
--    |
--    | 
-- Student     Marks    Rank
-- --------    -----    ----
-- A           95        1
-- B           90        2
-- C           85        3
-- D           80        4

-- ROW_NUMBER()
-- Everyone gets a unique seat number.
-- 1
-- 2
-- 3
-- 4

-- RANK()
-- Ties share the rank, and gaps appear.
-- 1
-- 1
-- 3
-- 4

-- DENSE_RANK()
-- Ties share the rank, but no gaps.
-- 1
-- 1
-- 2
-- 3



-- Q1 — Customer order ranking
-- Using orders, display:
-- customer_id
-- order_id
-- order_date
-- and assign each customer's orders a rank based on:
-- earliest order → highest rank

SELECT * FROM orders;

SELECT
     customer_id,
     order_id,
     order_date,
     RANK() OVER(
        PARTITION BY customer_id
        ORDER BY order_date
     )
FROM  orders
ORDER BY customer_id,order_date;


-- Q3 🔥 — Category ranking
-- Using products, display:
-- product_name
-- category
-- price
-- and assign a price rank within each category.
-- Use:
-- PARTITION BY category

SELECT * FROM products;

SELECT
    product_name,
    category,
    price,
    RANK() OVER(
        PARTITION BY category
        ORDER BY price DESC
    )
FROM products
ORDER BY category,price DESC;


-- Q5 — Revenue ranking
-- Using order_items, calculate the total revenue generated by each product and then rank the products from highest revenue to lowest revenue.
-- Return:
-- product_id
-- total_revenue
-- revenue_rank

SELECT * FROM order_items;

SELECT
    product_id,
    SUM(quantity * unit_price) AS total_revenue,
    RANK() OVER(
        ORDER BY SUM(quantity * unit_price) DESC
    ) AS revenue_rank
FROM order_items
GROUP BY product_id
ORDER BY revenue_rank;

-- Q6 🔥🔥 — Category top products
-- Find the top 2 highest-priced products in every category.
-- Return:
-- category
-- product_name
-- price
-- rank
-- Use DENSE_RANK().

SELECT * FROM products;

SELECT *
FROM(
    SELECT
        category,
        product_name,
        price,
        DENSE_RANK() OVER ( 
            PARTITION BY category
            ORDER BY price DESC
        ) AS rank
    FROM products
) sub
WHERE rank <=2;